### ISSUE TITLE
can't go get

### ISSUE THREAD

**Issue by aircjm** [gogap/go-pandoc#3]
![image](https://user-images.githubusercontent.com/18283183/57063938-75c3d100-6cf7-11e9-88f0-1ebf9ed8f1b1.png)

**Comment by aircjm** [comment]
my go version is :
![image](https://user-images.githubusercontent.com/18283183/57066398-aa875680-6cfe-11e9-9304-9667f5ac38b2.png)

**Comment by xujinzheng** [comment]
this is os api issue, I think Windows did not support SysProcAttr, I will try fix this.

**Comment by aircjm** [comment]
OK ,Thanks
